### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by Toilal** [EasyBatch/easybatch-framework#102]
Hi !

When `3.1.0` will be released ? I need the JPA writting feature available in current master, but the corporate proxy at my customer deny access to the snapshot repository, so I can't use `3.1.0-SNAPSHOT`. 

For this customer, I need to migrate a batch i've written with spring batch, because nobody has understood the spring batch configuration for an actually simple batch process.

So I've found this library with some googling, and was surprised to find you again @benas under this project ! You are really making good OSS, keep the good work and thanks for all.

**Comment by benas** [comment]
Hello Rémi,

Thank you very much for these kind words!

I've planned to release version 3.1 by the end of this week. I'm just finishing documentation updates and it should be ready for GA.

Keep tuned.

Regards

**Comment by Toilal** [comment]
Great ! Thanks
