### ISSUE TITLE
RecordMarshaller doesn't work with JPA/Hibernate reader

### ISSUE THREAD

**Issue by Toilal** [EasyBatch/easybatch-framework#108]
JPA/Hibernate use CGLIB to create proxies of JPA Entities.

Problem is that most RecordMarshaller implementations use the writer Method obtained from the original class (given by the user it's in the constructor).

So the record instance beeing processed by the marshaller is a CGLIB Proxy of this original class, it's not the real class.

It's weird, but in this case, trying to call [invoke(object)](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-integration/easybatch-apache-commons-csv/src/main/java/org/easybatch/integration/apache/common/csv/ApacheCommonCsvRecordMarshaller.java#L93-L95) gives an error because of JDK internal checkings.

```
java.lang.IllegalArgumentException: object is not an instance of declaring class
```

**Comment by Toilal** [comment]
Oh sorry about that, I was totally wrong in the analysis and the issue is really simpler ... I'll open a PR !

**Comment by benas** [comment]
Hey! Pas de souci :-) tu viens sur [https://gitter.im/EasyBatch/easybatch-framework] vite fait?

**Comment by Toilal** [comment]
`.mapper(new GenericRecordMapper())` has fixed this.

**Comment by benas** [comment]
As discussed, I've added a note about this point [here](https://github.com/EasyBatch/easybatch-website/blob/master/_includes/user-guide/processing.html#L224). Record marshallers expect Java objects as input.
