### ISSUE TITLE
Add support for univocity-parsers

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#121]
Add an integration module with [univocity-parsers](https://github.com/uniVocity/univocity-parsers) to read and write flat formats. 

Also add a mapper based on the [BeanProcessor](https://github.com/uniVocity/univocity-parsers#using-annotations-to-map-your-java-beans).

**Comment by benas** [comment]
Hi @anthony-bruno and @jbax

First, I would like to thank you for the great work on uniVocity!

It has been a while since I wanted to add an extension to easy batch for uniVocity parser but never got time to do it (see history of this issue). Do you think you can help a little? It would be great to join forces and add this extension. I'm not sure this would require a lot of work (a couple of classes), and I think you are  best placed to contribute them.

What do you think? If you agree, I would be very grateful!
If you can't, no worries, I'll still try to find time to do it myself. 

Kind regards
Mahmoud

**Comment by jbax** [comment]
Thanks for the invitation, but we currently got a lot of work to do and are short of time available. We'll be happy to assist in case you have questions, but won't be able to actively assist you with coding/testing. We really appreciate your initiative to integrate our parsers into your library, cheers!

**Comment by benas** [comment]
That's fine, no problem.
Keep your good work on uniVocity up!

**Comment by benas** [comment]
Hi @jbax and @AussieGuy0 

I wish you a happy new year!

Many thanks to Anthony for adding support for univocity parsers to easy batch ( #258 ).

I'm closing this issue as it will be included in the upcoming release 5.1.

Best regards
Mahmoud
