### ISSUE TITLE
Add support for MS excel format using Apache POI

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#123]
Add reader and writer for MS Excel format using [Apache POI](https://poi.apache.org/)

**Comment by sothavirak** [comment]
Hi,

**Comment by benas** [comment]
Hi,

There is no due date, it depends on the progress. There is a branch named `easybatch-msexcel` where I am experimenting with Apache POI. See example [here](https://github.com/EasyBatch/easybatch-framework/blob/easybatch-msexcel/easybatch-extensions/easybatch-msexcel/src/test/java/org/easybatch/extensions/msexcel/MsExcelSupportIntegrationTest.java).

Here is the current status of the branch:

- [x] MsExcelRecord
- [x] MsExcelRecordReader
- [x] MsExcelRecordMapper
- [ ] MsExcelRecordMarshaller
- [ ] MsExcelRecordWriter

You can already try it by [importing](https://github.com/EasyBatch/easybatch-framework#current-version) the `4.1.0-SNAPSHOT` version in your project.

The current reader supports only xls format, you are welcome to add support for xlsx from your implementation.

BTW, are you using the latest version 4.0? If not, I strongly recommend you to upgrade, this is the best release so far! Would love to hear your thought on this new version :-)

Regards
Mahmoud

**Comment by sothavirak** [comment]
Hi Mahmoud,

Yes we are using version 4.0 and we love it :)... As for xlsx support, our requirement is to be able to read both format by replacing one line in your MsExcelRecordReader.java

HSSFWorkbook workbook = new HSSFWorkbook(new FileInputStream(file));

with 

Workbook workbook = WorkbookFactory.create(new FileInputStream(file));

Thanks for the great work. This framework is rock!

Regards,
Sothavirak

**Comment by benas** [comment]
Thank you for this kind feedback! I'm glad you like it :-)

I was thinking about making the MsExcel format as a second parameter to the `MsExcelRecordReader`:

```
File tweets = new File("tweets.xls");
Job job = JobBuilder.aNewJob()
      .reader(new MsExcelRecordReader(tweets , MsExcelFormat.XLS)) // or MsExcelFormat.XLSX
      .build();
```

Or may be other names for the constants, but the idea is to make the format configurable at construction time to support both versions.

The work is in progress, keep tuned. You are welcome to contribute if you want!

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi Sothavirak,

It took some time, but it is finally here :smile:  I've added support for MsExcel XLSX support in the master branch and will be released soon. Here are the main components:

* `MsExcelRecord`: record having apache POI `Row` as payload
* `MsExcelRecordReader`: iteratively read `MsExcelRecord`s from a xlsx file (streaming will be added later on)
* `MsExcelRecordMapper`: map rows to POJOs
* `MsExcelRecordMarshaller`: marshal POJOs to rows
* `MsExcelRecordWriter`: write rows to a sheet in a xlsx file

I've decided to support only the new format (xlsx) but not the legacy one (xls).

It would be great if you can try it with version `4.1.0-SNAPSHOT` and give me your feedback. An example can be found [here](https://github.com/EasyBatch/easybatch-framework/blob/easybatch-msexcel/easybatch-extensions/easybatch-msexcel/src/test/java/org/easybatch/extensions/msexcel/MsExcelSupportIntegrationTest.java).

Kind regards
Mahmoud

**Comment by benas** [comment]
I'm preparing to release v4.1 including this feature.

If you have any issue, please file a bug.
