### ISSUE TITLE
Consider usage of Log4j rather than java.util.logging?

### ISSUE THREAD

**Issue by iwhitfield** [EasyBatch/easybatch-framework#125]
Typically Log4j offers much better support for customising logs (particularly for the end-users of this library). Is there any reason this library couldn't be moved over? I'd be happy to open a PR, if necessary.

**Comment by benas** [comment]
Hi, please refer to question 8 of the [FAQ section](http://www.easybatch.org/documentation/faq.html).
The choice of using JUL has been made because we want the framework's core to have zero dependencies.

**Comment by iwhitfield** [comment]
@benas I figured that could be the case when I spotted no dependencies bundled in the pom.xml :p works for me as a valid reason, anyway.

**Comment by benas** [comment]
Have you been able to customise JUL on AWS beanstalk?

**Comment by iwhitfield** [comment]
@benas yeah we were having some issues for a while, but it looks like they point their Tomcat to their own properties file - once we found that it's all good.
