### ISSUE TITLE
Feature Request - Conditional Processing

### ISSUE THREAD

**Issue by MALPI** [EasyBatch/easybatch-framework#128]
As already mentioned in glitter, It would be great if it would be possible to cancel a Batchjob from "inside" the engine.

Lets assume you define in the listener a method to pull a file from remote, which is only created under special circumstances.
Instead of letting the engine fail by exception you could call then `engine.cancel` in the `beforeJobStart`method of the JobListener and cancel the job gracefully.

I hope it's clear what I mean.

**Comment by benas** [comment]
Hello,

Thank you for this feature request.

The engine is a `Callable` object, we can't call `engine.cancel` on it.
Even though in most example we call the `call` method directly on the engine, you should see the engine as a unit f work that need to be submitted to an executor service which is responsible for it's life cycle (start, stop, cancel, calculate progress, handle timeout, etc).

So if you need to cancel a engine under certain circumstances, you can use an executor service for that:

```java
Engine engine = ...
ExecutorService executorService = Executors.newSingleThreadExecutor();

Future<Report> report = executorService.submit(engine);

if (needToCancelJob()) {
   report.cancel(true);
}

 executorService.shutdown();
```

We can even imagine an admin GUI for jobs submitted to an executor service through which we can start/stop/cancel jobs, monitor their progress, etc (which I planned for a future release). 

Moreover, when I implement a `JobEventListener`, I don't have access to the engine in the scope of the `beforeJobStart` method, so it's not possible to "cancel" the engine there. This listener should not be aware of the engine in which it is registered, and most importantly, should not act on its life cycle (cancel, start, stop). This is the role of the executor service.

What are your thoughts on that?

Regards
Mahmoud

**Comment by MALPI** [comment]
Actually, the executorservice might be an option. I also understand that the eventListener shouldn't be aware of the engine itself.

Nevertheless I'd like to see a direct integration in easybatch for this kind of functionality. Maybe it would also be an option to create a module, where the user is able to define preconditions which need to be fulfilled for a certain job?

**Comment by benas** [comment]
This has been discussed in [issue 66](https://github.com/EasyBatch/easybatch-framework/issues/66).
I invite you to read this thread to have an idea about the feature as requested by other users.

As you said, it can be a separate module to orchestrate Easy Batch jobs (conditional starts, job chaining, branching, etc). This is a good use case to try to integrate with one of the existing orchestration/workflow engines in Java

**Comment by MALPI** [comment]
Duplicate of #66
