### ISSUE TITLE
custom BatchReader error

### ISSUE THREAD

**Issue by echang** [EasyBatch/easybatch-framework#164]
Hello,

I tried to create a batch reader for the JMSQueueRecordReader, but when I compile it i got the following error:
com.company.reader.JmsQueueBatchReader is not abstract and does not override abstract method readNextRecord() in org.easybatch.core.reader.RecordReader

I tried creating a exact same IterableBatchReader here too and get the same error,if I directly use it from the EasyBatch library, it is fine. Below is my code, could you please help me see what went wrong?

Thanks!!
Eric

package com.company.reader;

import org.easybatch.core.reader.AbstractBatchReader;
import org.easybatch.core.reader.RecordReader;
import org.easybatch.core.reader.RecordReadingException;
import org.easybatch.core.record.Batch;
import org.easybatch.core.record.Header;
import org.easybatch.core.record.Record;
import org.easybatch.jms.JmsQueueRecordReader;

import java.util.ArrayList;
import java.util.Date;

public class JmsQueueBatchReader extends AbstractBatchReader {

    public JmsQueueBatchReader(final int batchSize,final JmsQueueRecordReader recordReader) {
        super(batchSize, recordReader);
    }

}

**Comment by benas** [comment]
Hi,

I noticed you closed this issue, have you found a solution?

Kind regards
Mahmoud

**Comment by echang** [comment]
Thanks for the reply Mahmoud! I moved the jar files to a more proper location then the compiler did not complain. I am doing the end to end testing of my process now and might have more questions about the EasyBatch for you later:-)

Thanks!
Erick

**Comment by benas** [comment]
Cool :-)

Please do not hesitate to ask me for support, I would love to help.

Regards
Mahmoud

**Comment by echang** [comment]
Thanks a lot in advance! Really appreciate it!

Thanks,
Erick
