### ISSUE TITLE
asynchronous between pipelines

### ISSUE THREAD

**Issue by echang** [EasyBatch/easybatch-framework#166]
Hi Mahmoud,

Not sure if here is the right place to ask, is there any way we can run pipeline processors asynchronously? Such as adding buffers in between processors.

Thanks,
Erick

**Comment by benas** [comment]
Hi Erick and happy new year :smile: 

Currently the pipeline execution is synchronous.
I've planned to add asynchronous support in the next release, this will significantly improve the performance of the pipeline execution.

I have the idea to use blocking queues (with different configurable strategies) as record buffers between processors.

Kind regards
Mahmoud

**Comment by echang** [comment]
Happy new year Mahmoud,

That's great news! Thanks! Do you know when the next release is gonna be? I am thinking of some alternatives for the asynchronous pipeline. Maybe I can split the processors into a few jobs and create blocking queues between jobs and have the round robin dispatcher at the end of every job before the last job. So the job here is more like a pipeline stage. Does that make any sense to you?

Thanks! Can't wait to see your next release.
Erick

**Comment by echang** [comment]
Hi Mahmoud,

I tried to build an alternative asynchronous pipeline by using jobs and blockingqueue as the buffer in between, please see the sample from the link https://gist.github.com/echang/d38c021b8282a0d9915c 

The database source reading job the the paralleled job1s seem to work well, and job1s end gracefully after processing all the items in the queues inserted by the source reading job, however, if I add a PoisonRecordBroadcaster in the jobListener in Job1 for the job2 to exit after processing all the records, job 2 got stopped right away before it can process any record.

 Is there other mechanism to exit a job after all records are processed instead of using PoisonRecordBroadcaster?

Thanks,
Erick

**Comment by echang** [comment]
Hi Mahmoud,

I added the comment in my gist, not sure if it  sent out the notification. 


Thanks,
Erick

**Comment by benas** [comment]
Hi Erick,

I was working on this issue the last few days hoping to release it in the upcoming version 4.1. Introducing queues as buffers between processors requires a major work on the code base, so it will wait until the next major release 5.0 (which will be Java 8 compatible BTW).

My first impression is that each processor will have its "work" queue, and this can consume a lot of memory whenever there are many processors in the pipeline. Introducing async pipeline support will be probably faster, but certainly less memory efficient. Java 8's streams are not asynchronous.

Can you please remind me what was your motivation when you first asked for this feature?

Kind regards
Mahmoud

**Comment by echang** [comment]
Hi Mahmoud,

Glad to hear from you!

My motivation is that when a record needs to go through multiple
processors, if any of the processors take a bit longer, then the backlog
will start since it is a synchronous job, it is hard to scale the system I
am building given the huge volume of the data I am dealing with. By doing
it asynchronously,  a processor can just send the processed record to the
next queue for the next processor to pick up, records will waits in the
memory buffer, or we can even use file buffer in order to resume the work
in the pipeline when it fails. Also we can make the queue/buffer size
configurable to better control the usage of the memory, of course if any
processor is way too slow then we will still fill up the buffer and the
backlog will start again, but that's when we need to work more on the
processor itself and maybe add a throttle control at source etc. I also
need to have multiple same processors running in parallel ( one queue/
buffer  for multiple parallel same processors)  and we can configure how
many paralleled same processors we want. The job should exit gracefully
when we are done processing all records.

Please feel free to let me know if anything sounds confusing and anything I
can help with, I'd be more than happy to help:)

Thanks,
Erick

**Comment by benas** [comment]
I see. This is also what I planned to do as described in my [previous comment](https://github.com/EasyBatch/easybatch-framework/issues/166#issuecomment-169271462). Here is a first draft:

![image](https://cloud.githubusercontent.com/assets/1210553/16303424/e336d314-3950-11e6-8bbd-3f5cdc9336b7.png)

I will introduce the concept of "stage". Each stage has a buffer of work. In each stage, the processor can be executed in sequence or in parallel (ex stage 2 here with a degree of parallelism of 3).

> I also need to have multiple same processors running in parallel ( one queue/
buffer  for multiple parallel same processors)  and we can configure how
many paralleled same processors we want.

Yes, as in stage 2 in the previous example. The DOP will be configurable in the job DSL.

I think v5 will be quite interesting :smile:

**Comment by echang** [comment]
Awesome, can't wait to see it happen:)
Please don't hesitate to let me know if anything I can help, e.g. testing
or trial etc.

Thanks,
Erick

**Comment by benas** [comment]
Hi Erick,

I was busy the last few days working on v5. There are some design issues with v4 which I summarized in issue #211 . Do you think asynchronous processing is still relevant with the new proposed workflow (which is inspired by JSR 352 BTW) ? I do believe that asynchronous and parallel processing should be done in the natural way of dispatching records (see [fork/join tutorial](https://github.com/EasyBatch/easybatch-tutorials/blob/master/src/main/java/org/easybatch/tutorials/advanced/parallel/ForkJoinTutorial.java)). What do you think?

> Please don't hesitate to let me know if anything I can help, e.g. testing
> or trial etc.

Thank you! Actually I've published version 5.0.0-SNAPSHOT. It would be grateful to you if you can try it out and give me feedback :smile: 

Kind regards
Mahmoud

**Comment by benas** [comment]
I think this feature can be implemented by extending a record processor (the decorator pattern) instead of modifying the framework to support it (Open/Closed principle). Why not simply having a `CompositeAsynchronousProcessor` which delegates processing to regular processors and handles asynchronous processing using queues as buffers? Something like:

```java
Job job = JobBuilder.aNewJob()
   .reader(myReader)
   .processor(new CompositeAsynchronousProcessor(myProcessor1, myProcessor2))
   .build();
```

What do you think?

**Comment by echang** [comment]
Hello Mahmoud,

Sorry I got sidetracked and didn't get a chance to get back to you, let me take a look at it and get back to you more on it, it sounds like a good way to do it, is there any way that we can configure our own buffer size?

Thanks,
Erick

**Comment by benas** [comment]
Hi Erick,

FYI, v5 is finally out!

> is there any way that we can configure our own buffer size?

IMO this is possible since we have control on the implementation details of such a `CompositeAsynchronousProcessor`. The buffer size can be set at construction time or with a setter.

Probably registering only this processor (containing composing processors and queues) in the job and let easy batch read records and pass them to it. Do you see?

> I think this feature can be implemented by extending a record processor (the decorator pattern) instead of modifying the framework to support it (Open/Closed principle).

I'm closing this issue since I'm not sure we really need to modify the current workflow. 

Kind regards
Mahmoud

**Comment by naivefun** [comment]
... where is the async support in 6.1.0?

**Comment by benas** [comment]
@naivefun As mentioned in my previous [comment](https://github.com/j-easy/easy-batch/issues/166#issuecomment-249902367), this can be achieved with a custom async processor instead of changing the framework's workflow.
