### ISSUE TITLE
Unable to determine reason for read failure/exception

### ISSUE THREAD

**Issue by chazo** [EasyBatch/easybatch-framework#168]
if the reader fails, for example a file that does not exist is passed to FlatFileRecordReader, an exception is logged, but, there is no way to programmatically find the reason for the failure. The exception should be stored in the Job report.

**Comment by benas** [comment]
Hi,

Good idea indeed, I'll add the last error in the job report to be able to get it programmatically when the job is aborted or failed.

Regards
Mahmoud

**Comment by benas** [comment]
Hi,

I've added the last error (if any) in the job report. you can get access to it programmatically with `jobReport.getMetrics().getLastError()`. You can give it a try in the 4.1.0-SNAPSHOT version.

Looking forward for your feedback.
Cheers
Mahmoud

**Comment by benas** [comment]
I'm preparing to release v4.1 including this fix.

If you have any issue, please file a bug.
