### ISSUE TITLE
Add support to trim whitespace for FixedLengthRecordMapper

### ISSUE THREAD

**Issue by sothavirak** [EasyBatch/easybatch-framework#171]
Can we have the same capability like DelimitedRecordMapper to trimWhitespaces? Thanks.

**Comment by benas** [comment]
Hi,

Thank you for requesting this feature.

I've added support to trim whitespaces in the `FixedLengthRecordMapper` (example [here](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-flatfile/src/test/java/org/easybatch/flatfile/FixedLengthRecordMapperTest.java#L69)).

You can give it a try with the current snapshot version (see [instructions](https://github.com/EasyBatch/easybatch-framework#current-version) on how to use it) and keep me informed in case of any issue.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @sothavirak 

Have you been able to try this new feature?

Please let me know if everything is ok for you.

Kind regards
Mahmoud

**Comment by sothavirak** [comment]
Hi @benas 

Working good :+1:  Thanks :)

Regards,
Khy
