### ISSUE TITLE
Possible bug in XmlReader

### ISSUE THREAD

**Issue by eugene-kamenev** [EasyBatch/easybatch-framework#172]
I am not sure, maybe it is based on implementation of jaxb, in my case https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-xml/src/main/java/org/easybatch/xml/XmlRecordReader.java#L111 this call delegates to Object.toString(). I am sure you can do 
```java
xmlEvent.asCharacters().getData()
``` 
no?

**Comment by benas** [comment]
Hi,

Thank you for pointing out this detail. Indeed it's better with `xmlEvent.asCharacters().getData()`. I just fixed that, unit and integration are green so everything is ok :smile: 

Thanks
Regards

**Comment by eugene-kamenev** [comment]
XmlEvent is an interface itself, so you dont know what kind of object will be called toString(). Then i found that i need to escape xmlEvent.asCharacters().getData() beacause it is raw data. And overall, thanks, I am trying to adapt your library for our jobs, but seems that we need custom xml reader because yours is not so smart, it cuts many needed things from input xml, then we have valid complex types defined in xsd and mapped to java classes. If I will create XmlRecord() manually passing whole xml, unmarshalling in XmlMapper works fine. We have xsd also, and this thing does not work if you cut xmlns="" schema information. However it is fine for simple xml files like in your examples.

**Comment by benas** [comment]
Thank you for these details.

>  I am trying to adapt your library for our jobs

Cool, don't hesitate to ask me if you need support. We can also try to improve Easy Batch so it can cover your requirements. What are you trying to adapt?

> we need custom xml reader because yours is not so smart, it cuts many needed things from input xml

Can you give me an example please? How can I make it smarter?

> this thing does not work if you cut xmlns="" schema information.

There is an example with custom namespace and xsd [here](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-xml/src/test/java/org/easybatch/xml/XmlIntegrationTest.java#L162), it's about reading beans from a Spring configuration file. Is your use case different?

**Comment by benas** [comment]
Hi @eugene-kamenev ,

Any update on this issue?

**Comment by eugene-kamenev** [comment]
Hi, you can close this. Just wanted to thank you, your framework did the
job. But we customized it a bit for our xml usage.
14 марта 2016 г. 4:19 PM пользователь "Mahmoud Ben Hassine" <
notifications@github.com> написал:
