### ISSUE TITLE
FlatFileRecordReader is not available in the Reader Class

### ISSUE THREAD

**Issue by anilkulkarni87** [EasyBatch/easybatch-framework#176]
Hi,
The Hello World example displays the below method:
```
Job job = new JobBuilder()
            .named("hello world job")
            .reader(new FlatFileRecordReader(dataSource))
```

The **FlatFileRecordReader ** is not available. Can you please confirm?

**Comment by benas** [comment]
Hi,

The `FlatFileRecordReader` is in the `easybatch-flatfile` module.

Have you added this module to your dependencies? If you follow the instructions on how to run the tutorial (section 6), everything should be correctly imported.

Please let me know if you were able to run the sample.

Kind regards
Mahmoud

**Comment by anilkulkarni87** [comment]
Yes adding that dependency worked. I was trying to get the output in
Eclipse IDE itself. and wasnt aware that there were other modules that had
to be added in dependency.

Thanks
Anil

On Thu, Feb 25, 2016 at 6:15 PM, Mahmoud Ben Hassine <
notifications@github.com> wrote:

> Hi,
>
> The FlatFileRecordReader is in the easybatch-flatfile module.
>
> Have you added this module to your dependencies? If you follow the
> instructions on how to run the tutorial (section 6), everything should be
> correctly imported.
>
> Please let me know if you were able to run the sample.
>
> Kind regards
> Mahmoud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-189080222>
> .
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by benas** [comment]
Glad to hear it works for you now.

Don't hesitate to ask for support if needed! I would love to help.

Kind regards

**Comment by anilkulkarni87** [comment]
Hi Mahmoud,

Thanks for the prompt reply. This is the first time am trying Easybatch.
now i am stuck at another place.

My Code:
  public static void main( String[] args ) throws FileNotFoundException
    {
        System.out.println( "Hello World!" );

        File dataSource=new File("Sample");
        System.out.println(dataSource.getAbsolutePath());
        System.out.println(dataSource.canRead());
        DelimitedRecordMapper datamapper=new
DelimitedRecordMapper(N01MemberPermissions.class, Listed all fields here");
        datamapper.setDelimiter("|");

        Job job= JobBuilder.aNewJob()
        .named("Hello World Job")
        .reader(new FlatFileRecordReader(dataSource))
        .filter(new StartWithStringRecordFilter("FH"))
        .filter(new StartWithStringRecordFilter("FT"))
        .mapper(datamapper)
        .validator(new BeanValidationRecordValidator<Sample>())
        .writer(new StandardOutputRecordWriter())
        .build();

        JobReport report=JobExecutor.execute(job);
        System.out.println(report);
    }
}


Error:
org.easybatch.core.mapper.RecordMappingException: Unable to create a new
instance of target type com.test.bean.Sample



On Fri, Feb 26, 2016 at 1:59 AM, Mahmoud Ben Hassine <
notifications@github.com> wrote:

> Glad to hear it works for you now.
>
> Don't hesitate to ask for support if needed! I would love to help.
>
> Kind regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-189200703>
> .
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by benas** [comment]
Hi,

Your record mapper tries to map `StringRecord`s to instances of `N01MemberPermissions.class`. Looks like the mapper is not able to create a new instance of the `com.test.bean.Sample` type. Is this class public? Is it nested in the `N01MemberPermissions.class`? This can be the reason of the issue.

Also, note that the output of the mapper is the input of the validator according to your job description. Since the mapper will produce N01MemberPermissions.class objects, the validator should then validate N01MemberPermissions.class objects (not Sample objects):

```java
.validator(new BeanValidationRecordValidator< N01MemberPermissions>())
```

Do you see?

Kind regards
Mahmoud

**Comment by anilkulkarni87** [comment]
Hi,

Sorry for the confusion. You could replace Sample with N01MemberPermissions
int he code i sent above. But it still gives me the same error. And the
class N01MemberPermissions is public.


On Sun, Feb 28, 2016 at 1:06 PM, Mahmoud Ben Hassine <
notifications@github.com> wrote:

> Hi,
>
> Your record mapper tries to map StringRecords to instances of
> N01MemberPermissions.class. Looks like the mapper is not able to create a
> new instance of the com.test.bean.Sample type. Is this class public? Is
> it nested in the N01MemberPermissions.class? This can be the reason of
> the issue.
>
> Also, note that the output of the mapper is the input of the validator
> according to your job description. Since the mapper will produce
> N01MemberPermissions.class objects, the validator should then validate
> N01MemberPermissions.class objects (not Sample objects):
>
> .validator(new BeanValidationRecordValidator< N01MemberPermissions>())
>
> Do you see?
>
> Kind regards
> Mahmoud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-189946266>
> .
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by anilkulkarni87** [comment]
Ok Another update on this problem. The issue with instantiating is resolved.

Reason : I was missing the constructor in the N01MemberPermissions class.
It had only the parametrized constructor. Adding the below resolved that
problem.

public N01MemberPermissions(){
}


The new error is :
WARNING: No public setter found for field <Fieldname>, this field will be
set to null (if object type) or default value (if primitive type)

On Mon, Feb 29, 2016 at 9:41 AM, Anil Kulkarni <anil77k@gmail.com> wrote:

> Hi,
>
> Sorry for the confusion. You could replace Sample with N01MemberPermissions
> int he code i sent above. But it still gives me the same error. And the
> class N01MemberPermissions is public.
>
>
> On Sun, Feb 28, 2016 at 1:06 PM, Mahmoud Ben Hassine <
> notifications@github.com> wrote:
>
>> Hi,
>>
>> Your record mapper tries to map StringRecords to instances of
>> N01MemberPermissions.class. Looks like the mapper is not able to create
>> a new instance of the com.test.bean.Sample type. Is this class public?
>> Is it nested in the N01MemberPermissions.class? This can be the reason
>> of the issue.
>>
>> Also, note that the output of the mapper is the input of the validator
>> according to your job description. Since the mapper will produce
>> N01MemberPermissions.class objects, the validator should then validate
>> N01MemberPermissions.class objects (not Sample objects):
>>
>> .validator(new BeanValidationRecordValidator< N01MemberPermissions>())
>>
>> Do you see?
>>
>> Kind regards
>> Mahmoud
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-189946266>
>> .
>>
>
>
>
> --
> Cheers,
> Anil Kulkarni
> about.me/anilkulkarni
> [image: Anil Kulkarni on about.me]
>  http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by anilkulkarni87** [comment]
Hi ,

This issue is completely resolved. Ma able to process and do basic
validation of the records from the file.

My Actual purpose:

Read records from file
Validate each record
       1) Not null and size conditions
        2) Validate if that specific fields is already present in DB - How
do i implement this validation any idea?
Apart from job report, return clean records and return error records as
well.

Thanks
Anil


On Mon, Feb 29, 2016 at 10:00 AM, Anil Kulkarni <anil77k@gmail.com> wrote:

> Ok Another update on this problem. The issue with instantiating is
> resolved.
>
> Reason : I was missing the constructor in the N01MemberPermissions class.
> It had only the parametrized constructor. Adding the below resolved that
> problem.
>
> public N01MemberPermissions(){
> }
>
>
> The new error is :
> WARNING: No public setter found for field <Fieldname>, this field will be
> set to null (if object type) or default value (if primitive type)
>
> On Mon, Feb 29, 2016 at 9:41 AM, Anil Kulkarni <anil77k@gmail.com> wrote:
>
>> Hi,
>>
>> Sorry for the confusion. You could replace Sample with N01MemberPermissions
>> int he code i sent above. But it still gives me the same error. And the
>> class N01MemberPermissions is public.
>>
>>
>> On Sun, Feb 28, 2016 at 1:06 PM, Mahmoud Ben Hassine <
>> notifications@github.com> wrote:
>>
>>> Hi,
>>>
>>> Your record mapper tries to map StringRecords to instances of
>>> N01MemberPermissions.class. Looks like the mapper is not able to create
>>> a new instance of the com.test.bean.Sample type. Is this class public?
>>> Is it nested in the N01MemberPermissions.class? This can be the reason
>>> of the issue.
>>>
>>> Also, note that the output of the mapper is the input of the validator
>>> according to your job description. Since the mapper will produce
>>> N01MemberPermissions.class objects, the validator should then validate
>>> N01MemberPermissions.class objects (not Sample objects):
>>>
>>> .validator(new BeanValidationRecordValidator< N01MemberPermissions>())
>>>
>>> Do you see?
>>>
>>> Kind regards
>>> Mahmoud
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-189946266>
>>> .
>>>
>>
>>
>>
>> --
>> Cheers,
>> Anil Kulkarni
>> about.me/anilkulkarni
>> [image: Anil Kulkarni on about.me]
>>  http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>
>>
>
>
>
> --
> Cheers,
> Anil Kulkarni
> about.me/anilkulkarni
> [image: Anil Kulkarni on about.me]
>  http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by benas** [comment]
Hi Anil,

Looks like your use case is a bit similar to this [tutorial](http://www.easybatch.org/tutorials/loading-data.html): read data -> filter -> map -> validate -> write. This may help you.

I know that your resolved your mapping issue, but just FYI, Easy Batch mappers expect a standard Java bean as target object (ie, your bean must provide a default constructor and a public setter for each property).

Now to answer your question on database validation, you can implement the `RecordValidator` interface with your custom validation logic, being against a database or other storage and register it in the pipeline. You can register as many validators as you want:

```java
.validator(new BeanValidationRecordValidator< N01MemberPermissions>())
.validator(new MyCustomDbValidator())
```

Easy Batch will apply all validators in declaration order and reject invalid records. (See "Validators" section in the [user guide](http://www.easybatch.org/documentation/components-reference.html))

Kind regards
Mahmoud

**Comment by anilkulkarni87** [comment]
Thanks for the support.

I will work on the Custom Validator and get back if i have more questions.


Thank you so much!

On Mon, Feb 29, 2016 at 9:01 PM, Mahmoud Ben Hassine <
notifications@github.com> wrote:

> Hi Anil,
>
> Looks like your use case is a bit similar to this tutorial
> <http://www.easybatch.org/tutorials/loading-data.html>: read data ->
> filter -> map -> validate -> write. This may help you.
>
> I know that your resolved your mapping issue, but just FYI, Easy Batch
> mappers expect a standard Java bean as target object (ie, your bean must
> provide a default constructor and a public setter for each property).
>
> Now to answer your question on database validation, you can implement the
> RecordValidator interface with your custom validation logic, being
> against a database or other storage and register it in the pipeline. You
> can register as many validators as you want:
>
> .validator(new BeanValidationRecordValidator< N01MemberPermissions>())
> .validator(new MyCustomDbValidator())
>
> Easy Batch will apply all validators in declaration order and reject
> invalid records. (See "Validators" section in the user guide
> <http://www.easybatch.org/documentation/components-reference.html>)
>
> Kind regards
> Mahmoud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-190547509>
> .
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by anilkulkarni87** [comment]
Hi Mahmoud,


Would you be able to share any code where you have implemented any Custom
Validator?
I created a Custom Validator like the below. But i am unable to extract
field by field and do my validation. The payload returns the entire
delimited line from the file,

public class MyCustomValidator<Sample> implements
RecordValidator<GenericRecord<Sample>> {
public GenericRecord<Sample> processRecord(
GenericRecord<Sample> record)
throws RecordValidationException {
// TODO Auto-generated method stub
System.out.println(record.getPayload());
return record;
}

}


.filter(new StartWithStringRecordFilter("FH"))
        .filter(new StartWithStringRecordFilter("FT"))
        .mapper(datamapper)
        //.processor(new DelimitedRecordMarshaller(Sample.class,
Fieldsarray,"|"))
        .validator(new BeanValidationRecordValidator<Sample>())
        .validator(new MyCustomValidator<Sample>())

Assume that Sample is my Bean. I would like to access specific fields to do
custom validation in my CustomValidator.  Any help on this would be great.


On Mon, Feb 29, 2016 at 9:01 PM, Mahmoud Ben Hassine <
notifications@github.com> wrote:

> Hi Anil,
>
> Looks like your use case is a bit similar to this tutorial
> <http://www.easybatch.org/tutorials/loading-data.html>: read data ->
> filter -> map -> validate -> write. This may help you.
>
> I know that your resolved your mapping issue, but just FYI, Easy Batch
> mappers expect a standard Java bean as target object (ie, your bean must
> provide a default constructor and a public setter for each property).
>
> Now to answer your question on database validation, you can implement the
> RecordValidator interface with your custom validation logic, being
> against a database or other storage and register it in the pipeline. You
> can register as many validators as you want:
>
> .validator(new BeanValidationRecordValidator< N01MemberPermissions>())
> .validator(new MyCustomDbValidator())
>
> Easy Batch will apply all validators in declaration order and reject
> invalid records. (See "Validators" section in the user guide
> <http://www.easybatch.org/documentation/components-reference.html>)
>
> Kind regards
> Mahmoud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-190547509>
> .
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by anilkulkarni87** [comment]
Mahmoud,

I resolved the issue soon after i sent you the email. I dont think you need
spend your time on this.

Thank you

On Thu, Mar 3, 2016 at 4:53 PM, Anil Kulkarni <anil77k@gmail.com> wrote:

> Hi Mahmoud,
>
>
> Would you be able to share any code where you have implemented any Custom
> Validator?
> I created a Custom Validator like the below. But i am unable to extract
> field by field and do my validation. The payload returns the entire
> delimited line from the file,
>
> public class MyCustomValidator<Sample> implements
> RecordValidator<GenericRecord<Sample>> {
> public GenericRecord<Sample> processRecord(
> GenericRecord<Sample> record)
> throws RecordValidationException {
> // TODO Auto-generated method stub
> System.out.println(record.getPayload());
> return record;
> }
>
> }
>
>
> .filter(new StartWithStringRecordFilter("FH"))
>         .filter(new StartWithStringRecordFilter("FT"))
>         .mapper(datamapper)
>         //.processor(new DelimitedRecordMarshaller(Sample.class,
> Fieldsarray,"|"))
>         .validator(new BeanValidationRecordValidator<Sample>())
>         .validator(new MyCustomValidator<Sample>())
>
> Assume that Sample is my Bean. I would like to access specific fields to
> do custom validation in my CustomValidator.  Any help on this would be
> great.
>
>
> On Mon, Feb 29, 2016 at 9:01 PM, Mahmoud Ben Hassine <
> notifications@github.com> wrote:
>
>> Hi Anil,
>>
>> Looks like your use case is a bit similar to this tutorial
>> <http://www.easybatch.org/tutorials/loading-data.html>: read data ->
>> filter -> map -> validate -> write. This may help you.
>>
>> I know that your resolved your mapping issue, but just FYI, Easy Batch
>> mappers expect a standard Java bean as target object (ie, your bean must
>> provide a default constructor and a public setter for each property).
>>
>> Now to answer your question on database validation, you can implement the
>> RecordValidator interface with your custom validation logic, being
>> against a database or other storage and register it in the pipeline. You
>> can register as many validators as you want:
>>
>> .validator(new BeanValidationRecordValidator< N01MemberPermissions>())
>> .validator(new MyCustomDbValidator())
>>
>> Easy Batch will apply all validators in declaration order and reject
>> invalid records. (See "Validators" section in the user guide
>> <http://www.easybatch.org/documentation/components-reference.html>)
>>
>> Kind regards
>> Mahmoud
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-190547509>
>> .
>>
>
>
>
> --
> Cheers,
> Anil Kulkarni
> about.me/anilkulkarni
> [image: Anil Kulkarni on about.me]
>  http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>

**Comment by benas** [comment]
Hello, no problem.

If you like the project and want to support it, please give it a little star on github and speak about it :smile: 

Also, If you have any feedback, don't hesitate to file bugs or request feature or documentation update.

Kind regards
Mahmoud

**Comment by anilkulkarni87** [comment]
This helped me a lot. I am definitely giving it a star. and post some
examples on my blog too.

Thank you

On Thu, Mar 3, 2016 at 8:43 PM, Mahmoud Ben Hassine <
notifications@github.com> wrote:

> Hello, no problem.
>
> If you like the project and want to support it, please give it a little
> star on github and speak about it [image: :smile:]
>
> Also, If you have any feedback, don't hesitate to file bugs or request
> feature or documentation update.
>
> Kind regards
> Mahmoud
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyBatch/easybatch-framework/issues/176#issuecomment-192100651>
> .
>



-- 
Cheers,
Anil Kulkarni
about.me/anilkulkarni
[image: Anil Kulkarni on about.me]
 http://anilwrites.blogspot.com/ <http://about.me/anilkulkarni>
