### ISSUE TITLE
easybatch-flatfile bug reading file

### ISSUE THREAD

**Issue by arnauldSerge** [EasyBatch/easybatch-framework#177]
Hello, 

i try to read csv file(with 5000 lines). 
 i use flatfile reader.  
i get a correct total number but he did'nt process any line . 
in Engine.caller the hasnext() method get false even we are on the firt line. 
however, when i use a file with only 300 lines i didn't get this bug. 

Thank for this useful framework. 

I use the 3.0.0 version

**Comment by benas** [comment]
Hi,

> i get a correct total number but he did'nt process any line . 

Have you registered any record processor?

> in Engine.caller the hasnext() method get false even we are on the firt line. 
however, when i use a file with only 300 lines i didn't get this bug.

Can you please give me your code to be able to reproduce the issue?
What is your OS? line separator may play a role..
What is the encoding of your file? Which Java version are your using?

Don't worry for the input file, I'll generate a dummy one with 5k lines.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

Any update on this issue?
It would be helpful to share a code snippet to let me reproduce the bug.

Thank you in advance
Kind regards
Mahmoud

**Comment by arnauldSerge** [comment]
Hi, 
thank for your attention on my issue, 
il still looking for the issu.  so you can find my code below




				final EngineBuilder builder = new EngineBuilder().reader(flatFileRecordReader)//
																 .mapper(delimiter)//
																 .validator(validatorHandler)//
																 .processor(new ReferentielProcessor(parameters))//
																 .errorRecordHandler(errorHandler)
																 .recordProcessorEventListener(new TransactionUnitProcessingEventListener(parameters))//
																 .batchProcessEventListener(new TransactionBlockProcessingEventListener(parameters, validatorHandler,errorHandler))
																 .ignoredRecordHandler(ignoreRecordHandler)
																 .strictMode(false);
				
				if (parameters.getIgnoreFirstLine()) {
					builder.filter(new HeaderRecordFilter());
				}
				
				builder.filter(new StartWithStringRecordFilter("#"));
				Engine engine = builder.build();
				report = engine.call();

**Comment by arnauldSerge** [comment]
In the Engine.call() methode at this 
            report.setTotalRecords(totalRecords);

i have a rigth total 

but when at    while (recordReader.hasNextRecord()) , i did'nt have any entry, it like it was at the end of the file

**Comment by arnauldSerge** [comment]
Hi, 
i realized that the issue occurs when i use a Charset  to create my flatFile, so i removed the charset. 


flatFileRecordReader=	new FlatFileRecordReader(loadfile,charset.name());

but i think i need a workaround  to fix this. 


Thank you so mutch for time you spend to help me

**Comment by benas** [comment]
Hi,

any update on this issue?

Have you tried to use the latest version 4.0.0 ? Please let me know it is the case.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

I really want to help on this. Do you need support to migrate your code to v4 line?

Kind regards
Mahmoud

**Comment by arnauldSerge** [comment]
Hello, i'm sorry, i have forgotten my password, so i found solution for my problem, 
i realized that according to the file encoding the framework interpret as end of file. 
So to avoid this i translate the content of the file in an ArrayList  then i used ListRecordReader.

**Comment by benas** [comment]
Hello, no problem, glad you found a solution.

If you need support, I'm eager to help!

Kind regards
Mahmoud
