### ISSUE TITLE
Add support of ZipOutputStream to write file as compressed archive

### ISSUE THREAD

**Issue by archenroot** [EasyBatch/easybatch-framework#179]
Hi, I really like EasyBatch first of all. I have some scenario where I would like to write directly to zip file, so I created:
CompressedFileWriter extends ZipOutputStreamRecordWriter
and 
public class ZipOutputStreamRecordWriter extends AbstractRecordWriter 

The issue is that i need to know when last record is processed and close the entry and whole zip file stream by calling methods:
ZipOutputStream.closeEntry();
ZipOutputStream.close();

I understand that for such/similar cases we have here job listeners. But the job listener gets only the result:
`@Override
    public void afterJobEnd(JobReport jobReport) {
 // I don't have access to the ZipOutputStream anymore to close the entry and the stream
    }
`
Thanks for hints or direction where to look into. I would like to follow architecture of easybatch, so I can share the code in github.

Ladislav

**Comment by archenroot** [comment]
Ok, now I understand this is going to be fixed also via custom job and pipeline listener (to close entry and close the stream itself in the very end). I will anyway extend the framework for Compress and Encrypt writers and/or Decrypt readers.

**Comment by archenroot** [comment]
I understand that for such cases we have here job listeners.

**Comment by benas** [comment]
Hi,

> I really like EasyBatch first of all

Thank you, I'm glad you like it :smile: 

> I understand that for such/similar cases we have here job listeners. But the job listener gets only the result:

```java
@Override 
public void afterJobEnd(JobReport jobReport) { 
// I don't have access to the ZipOutputStream anymore to close the entry and the stream 
} 
```

You can provide the stream to your listener at construction time. In the [csv to xml](http://www.easybatch.org/tutorials/csv2xml.html) tutorial, the [XmlWrapperTagWriter](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-xml/src/main/java/org/easybatch/xml/XmlWrapperTagWriter.java) is responsible for writing opening/closing tags around the output file content and closing the xml stream. This example may help you to implement your use case.

Hope this helps
Kind regards
Mahmoud

**Comment by archenroot** [comment]
I should have pointed that out by myself, shame on me :dancers: and thank you very much.

**Comment by benas** [comment]
Hi,

> I would like to put merge ZipOutputStream option into the project

Good Idea! Thanks for your suggestion

> Can you guide me how to implement it by following your architecture?

Sure. There is no a particular architecture, the goal is write the **payload** of each record the an output stream. You class design is correct, but I think you can create a `ZipOutputStreamRecordWriter` that extends the existent [OutputStreamRecordWriter](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-core/src/main/java/org/easybatch/core/writer/OutputStreamRecordWriter.java). Just provide a ZipOutputStream at creation time and you are done. You can take a look at the [StandardOutputRecordWriter](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-core/src/main/java/org/easybatch/core/writer/StandardOutputRecordWriter.java) to have an idea.
Hope this helps. Please don't hesitate to ask if you need further support!

> Similarly I would like to integrate PGP encrypted file stream.

Yes, please open a separate issue for this feature.

Many thanks upfront
Kind regards
Mahmoud

**Comment by archenroot** [comment]
Great, thanks for hints. This is what I have done so far :-)

The only issue is that the ZipOutputStream requires closeEntry() method to be called once all data are written. Where to put this piece of code?

Regards,
Ladislav

**Comment by benas** [comment]
Hi,

> Q1: The only issue is that the ZipOutputStream requires closeEntry() method to be called once all data are written. Where to put this piece of code?

This would be done in a job listener. Just like the xml sample above, we need two components with clear roles:

* a `ZipOutputStreamRecordWriter` that writes entries in the zip output stream (called for each record)
* a `ZipOutputStreamListener` which is responsible for opening/closing the stream (called once for all records).

Both components should be used together to accomplish the task.

> Q2: Should I create CompressedFileWriter as the main object wrapper?

I think we don't need a wrapper object. a `ZipOutputStreamWriter` is fine since there is already a `ZipOutputStream` in the standard library.

Kind regards
Mahmoud

**Comment by archenroot** [comment]
Completely agree. Will look into this, thx.

**Comment by benas** [comment]
Great, please open a pull request with a reference to this issue whenever you are ready.
