### ISSUE TITLE
Custom post/pre data processing - General question

### ISSUE THREAD

**Issue by archenroot** [EasyBatch/easybatch-framework#180]
While processing my sources I need to apply some pre/post processes over source/target data. My real example scenario is:
zip the file - custom CompressedFileWriter
encrypt the file - I will probably implement by custom EncryptStream or I am not sure in the moment
call Oracle PLSQL stored procedure
put file on FTP server
etc.

In general I would like to have some interface to implement custom processes whih will be considered(its results) as part of the job, so they will be reflected in job execution reports.

Thanks again for any hints if such feature exists already, looking into api.

**Comment by archenroot** [comment]
Ok, I understand now, that for such purpose we have here Job Listeners, cool. Thank you and I am closing the question.

**Comment by archenroot** [comment]
Ok, I understand now, that for such purpose we have here Job Listeners, cool. Thank you and I am closing the question.

**Comment by archenroot** [comment]
I understand that for such tasks like Oracle call and SFTP push we have here job listeners. Anyway question is in respect to Executor service which capture results of all threads:
Is the job thread fully considered as finished after these job listener tasks are also finished? So I can customize the result of Oracle call or SFTP push?

**Comment by benas** [comment]
> Is the job thread fully considered as finished after these job listener tasks are also finished?

Yes, if you submit an Easy Batch job to an executor service, you will get a `Future<JobReport>`. When the thread that executed your job returns the report, all phases of your job should have been executed (ie main processing + all listeners).

> In general I would like to have some other operations to be done within the Job. as far as I understand I will need to extend the Job class by new PostProcessing tasks, or something similar.

`Job` is an interface and its default implementation is [final](https://github.com/EasyBatch/easybatch-framework/blob/master/easybatch-core/src/main/java/org/easybatch/core/job/JobImpl.java#L45), not public and not designed to be extended. You can implement pre/post-processing using:

* A `PipelineListener` for a custom task per record
* A `JobListener` for a custom task per job

I have planned to introduce some utility listeners using these extension points such as:

* A job listener that would send the report by mail at the end of the job (issue #92)
* A job listener that would archive the input file in a configurable archive directory
* A job listener that would send the job output using FTP (like in your use case)

There are many other use cases that can be implemented using listeners.

**Comment by archenroot** [comment]
Thank you for explanation, it is clear to me now.

Yes, here I have SFTP(so it is not FTP, but SSH file transfer implemented via JSch libraries), but it doesn't matter that much :-)

What is related to this SFTP and for example database is that I implemented/reused existing pools, as soon as I process the jobs in parallel, it is more then clear that I should go with SFTP and Database pools(others as required, not my current case). 

I am not going to extend in the moment easybatch project for pools, but maybe we can consider this as new feature. So even you process in 100 threads, you limit the readers to for example 10 database connections, etc.

Thanks again for detailed reply.

Ladislav

**Comment by benas** [comment]
> So even you process in 100 threads, you limit the readers to for example 10 database connections, etc.

With Easy Batch, each job has its own reader. If you want to run 100 jobs in parallel, there will be 100 readers hitting your database. Now if your connection pool is sized to 10, 90 readers will wait until one  connection is available. You should tune your connection pool size to meet your performance target.

Please correct me if I'm wrong, is this what you are asking about?

> we can consider this as new feature

What is the requested feature here? Please update the title of the issue.
Any idea on how Easy Batch can help?

**Comment by archenroot** [comment]
> With Easy Batch, each job has its own reader. If you want to run 100 jobs in parallel, there will be 100 readers hitting your database. Now if your connection pool is sized to 10, 90 readers will wait until one connection is available. You should tune your connection pool size to meet your performance target.

This is exactly what I was facing yesterday :-) while playing with tuning the connection pools. I tried to run in massive parallel 1000(I have 64 core development beast with 64 GB ram) jobs with Oracle Connection pool limited to 10, so the process hanged after creating 9 jobs (I should expect 10 to be successfully created, will need to examine the behavior)

This leads me to something fundamental. Does the File or Database connection or any other connection be opened when the job is created by the method.
`private static Job buildJob` ? That is the question

I think the connection (FileInput/Output Stream, Database connection, any connection) can be open in the time when the job(Thread) is executed. That way we can create big parallel batch architecture independently on the infrastructure resource architecture. 

So it means that I can have 1000 jobs in the queue to be processed in parallel, I will define the thread pool size to 20 (max active threads in time), but if allow only 10 connections max in the pool. The result is that only 10 of 20 in the moment running threads will be working with database in time. But in general nothing gets blocked, the other threads will just wait until able to obtain connection from pool.

Similarly you can create File pool via apache-commons to provide any object pool, so I can limit the number of the files to be opened. 

Before I will rename or create new feature request, would like to confirm it is not against your ideas about easybatch project to not create connection/open file, etc on buildJob() method. Again this can be configurable with defaulting mechanism.

> we can consider this as new feature
What do you mean exactly, we already opened few things. I once we agree on few, I will register each one in separate request. This thread I would like to remain only for reference purposes and will reopen, so far I see following issues to be raised as feature requests:
- A job listener that would send the job output using FTP, FTPS(SSL encryption with implicit/explicit mode - Apache Commons Net dependency) and SFTP (SSH File Transfer Protocol - Jsch project dependency).
- A job listener that will call Oracle PL/SQL procedure via JDBC
- Support of Readers and Writers to work with ZipInput/OutputStream, so you can read/write directly from/to a zip/gzip, etc. files
- Support of Readers and Writers to Decrypt/Encrypt the file on the fly via  CipherInput/OutputStream

Regarding JobListeners: If I have 2 or more listeners are they executed in sequence as defined/attached to the job object?

**Comment by benas** [comment]
> This leads me to something fundamental. Does the File or Database connection or any other connection be opened when the job is created by the method.
private static Job buildJob ? That is the question

No, the `buildJob()` method simply creates the job object, it does not run it. The job is called when:

* you call the `call` method on the job instance
* Or call the `JobExecutor.execute(job)`
* Or the Executor service call your submitted job by an execution thread from the pool

> I think the connection (FileInput/Output Stream, Database connection, any connection) can be open in the time when the job(Thread) is executed.

Yes, this is the case currently as explained above

> So it means that I can have 1000 jobs in the queue to be processed in parallel, I will define the thread pool size to 20 (max active threads in time), but if allow only 10 connections max in the pool. The result is that only 10 of 20 in the moment running threads will be working with database in time. But in general nothing gets blocked, the other threads will just wait until able to obtain connection from pool.

Exact.

> Before I will rename or create new feature request, would like to confirm it is not against your ideas about easybatch project to not create connection/open file, etc on buildJob() method. Again this can be configurable with defaulting mechanism.

I'm not sure Easy Batch or any other framework can help at this level. Fine tuning is very specific to your performance target. Easy Batch helps you easily configure your jobs (and handles a lot of boilerplate for you), but it is up to you to find the best parameters for your thread pool and connection pool size. You gave some numbers about your experiments with different pool sizes, and I think this is a good empirical way to proceed.

> Regarding JobListeners: If I have 2 or more listeners are they executed in sequence as defined/attached to the job object?

Yes, they will be called in the order in which they were registered

**Comment by archenroot** [comment]
> No,  the buildJob() method simply creates the job object, it does not run it. The job is called when:
> you call the call method on the job instance
> Or call the JobExecutor.execute(job)
> Or the Executor service call your submitted job by an execution thread from the pool

I understand that this is really in my hands, so I can for example prepare batch of jobs to be executed, as soon as JdbcRecordReader will always take a database connection and possibly block the job to be created, I can alliteratively create and process smaller number of the jobs.

But I will probably will try to enhance this, as soon as I really would like to create 1000 jobs at once, but the database will never allow me to make such huge number of connections at same time.... Will look into this today. I think it is quite easy letting the JdbcRecordReader take only reference to the pool and on execution of the job, it will call pool.getConnection() method or similar....

**Comment by benas** [comment]
Hi

>  Will look into this today

Any update on this issue?

Cheers
Mahmoud

**Comment by benas** [comment]
I believe [this reply](https://github.com/EasyBatch/easybatch-framework/issues/180#issuecomment-189949423) answers your initial question. If you have any other question, don't hesitate to ask, I would love to help.

**Comment by benas** [comment]
Hi @archenroot 

I do believe the new version 5 of Easy Batch will help a lot in your case.

> I think the connection (FileInput/Output Stream, Database connection, any connection) can be open in the time when the job(Thread) is executed. That way we can create big parallel batch architecture independently on the infrastructure resource architecture.

With the new version, the `JdbcRecordReader` (and other readers) does not require a Jdbc connection at construction time. Instead, it should be supplied with a DataSource from which a connection will be opened/closed when the job starts/stops.

In v4, resource handling was handled by the user and not the framework. This was error prone and has been fixed in v5. See more details in issue #221 .

> So it means that I can have 1000 jobs in the queue to be processed in parallel

This is possible now with v5, you can create as many jobs as you want supplying them a pooled data source implementation, and the connections will be opened only when the jobs are executed. This was not possible with v4 because you had to open a connection and provide it to the reader at construction time..

v5 is clearly THE BEST release since the beginning of the project! I strongly recommend to migrate to v5. There is a migration guide [here](https://github.com/EasyBatch/easybatch-framework/releases/tag/easybatch-5.0.0-RC1), and I would be happy to help you migrate if you need support.

Best regards
Mahmoud
