### ISSUE TITLE
[Ask] Disable log for easy batch

### ISSUE THREAD

**Issue by stephendaniel** [EasyBatch/easybatch-framework#185]
Hi,

Is there any way to turn off the log in easy batch? Thanks.

**Comment by benas** [comment]
Hi,

Yes, you can set the `silentMode` parameter to disable logs:

```java
Job job = JobBuilder.aNewJob()
    .named("myJob")
    .silentMode(true)
    .build();
```

Alternatively, you can configure java util logging (used internally by easy batch). See question 8 of the [FAQ](http://www.easybatch.org/faq.html) section.

Hope this helps.
Kind regards
Mahmoud

**Comment by stephendaniel** [comment]
Hi,

Thank you very much for your help :) Really appreciate that.


Regards,

Stephen

**Comment by benas** [comment]
Great, glad it helped :smile:
