### ISSUE TITLE
"skip" parameter is redundant

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#212]
As of version 4.x, the semantic of "skip" is the same as "filter"

```java
Job job = new JobBuilder()
   .skip(1)
   .build();
```

is the same as:

```java
Job job = new JobBuilder()
   .filter(new RecordNumberLowerThanFilter(1))
   .build();
```

A more elegant way is to decorate a `RecordReader` with "skip" feature.

> "There should be one -- and preferably only one -- obvious way to do it", [The zen of python](There should be one-- and preferably only one --obvious way to do it)

"skip" parameter should be deprecated in v4.2 and removed in v5.x

**Comment by vian42** [comment]
it's the same as
```java
Job job = new JobBuilder()
   .filter(new RecordNumberLowerThanFilter(2))
   .build();
```

**Comment by strikerforce777** [comment]
skip(1) == RecordNumberLowerThanFilter(2)
