### ISSUE TITLE
Using MsExcelRecordReader file not closed after eof

### ISSUE THREAD

**Issue by packley1** [EasyBatch/easybatch-framework#237]
I'm using the MsExcelRecordReader class to read an Excel file.  Noticed that the file is not closed after EOF.  Manually inserted a close() call to the MsExcelRecordReader instance, but discovered it doesn't do anything.

**Comment by benas** [comment]
Hi,

Thank you for reporting! Which version are you using?

Kind regards
Mahmoud

**Comment by packley1** [comment]
Version=4.1.0

Thanks!

**Comment by benas** [comment]
Hi,

I've just deployed a fix in the 4.2.1-SNAPSHOT. Could you please give it a try?
To use snapshot versions, you need to add sonatype's snapshot repo. See details [here](https://github.com/EasyBatch/easybatch-framework#current-version).

FYI, v4.2 can be used as a drop-in replacement of v4.1. So using 4.2.1-SNAPSHOT should not cause any problem with your current code.

I'm ready  to help in any case.

Kind regards
Mahmoud

**Comment by packley1** [comment]
Awesome, thank you.  Yes this build fixes the issue.  Thanks much!

**Comment by benas** [comment]
Great! Thank you for testing!

I will release this fix soon in v4.2.1 and the upcoming 5.0.

Keep tuned.

**Comment by benas** [comment]
Hi,

I strongly recommend migrating to v5 which is released and contains the fix.

There is a migration guide [here ](https://github.com/EasyBatch/easybatch-framework/releases/tag/easybatch-5.0.0-RC1). Probably, in your case the migration will be easy.

I can help if you need support!

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi @packley1 

FYI, v4.2.1 has been released.

I highly recommend to migrate to v5 which also includes the fix. 
You can find a migration guide [here](https://github.com/EasyBatch/easybatch-framework/releases/tag/easybatch-5.0.0). I can help in the migration if needed.

Kind regards
Mahmoud
