### ISSUE TITLE
Processor causes Writer.writeBatch(batch) to get skipped.

### ISSUE THREAD

**Issue by RioTek** [EasyBatch/easybatch-framework#257]
Issue:  Writer.writeBatch() is skipped when used with a processor. Debugging shows it does hit the other functions in the Writer but not ".writeBatch(batch)". Also if a second processor is added, it also does not run after the first processor.

GOAL:  Fetch data from a file, use processor to apply EasyRules and modify data before writing to database.

WorkAround: Used the writerListener to apply rules prior to writing.  I'm not sure if there is a performance difference by doing this. Seems like processor is the appropriate place to apply rules.

    public class BatchLauncher2 {
    private static EntityManagerFactory entityManagerFactory;
    public static void main(String[] args) {
        entityManagerFactory = Persistence.createEntityManagerFactory("personEntityManager");

               File file = new File("src/test/resources/test.csv");

                OpenCsvRecordMapper recordMapper = new OpenCsvRecordMapper(Person.class,
                "field1","field2",);
                recordMapper.setQualifier('\"');

                // Processor
                RecordProcessor personRecordProcessor = new RecordProcessor();
                // ProviderRecordProcessor2 providerRecordProcessor2 = new ProviderRecordProcessor2();

                // Build a batch job
                Job job = JobBuilder.aNewJob()
                        .batchSize(2500)
                        .filter(new HeaderRecordFilter())
                        .reader(new PersonCsvRecordReader(file))
                        .mapper(recordMapper)
                        .processor(personRecordProcessor) // can't do .processor with .writer. skips writer.writeRecords().
                        // WorkAround: .writerListener(new PersonRecordWriterListener())
                        .writer(new PersonRecordWriter(entityManagerFactory))
                        .errorThreshold(2)
                        .build();

                // Execute the job
                JobExecutor jobExecutor = new JobExecutor();
                JobReport jobReport = jobExecutor.execute(job);
                jobExecutor.shutdown();
        }
   }

**Comment by benas** [comment]
Hi,

Thank you for reporting this issue! Probably your `personRecordProcessor` returns null ?

What does your processor do? This does not compile:

`RecordProcessor personRecordProcessor = new RecordProcessor();`

> Also if a second processor is added, it also does not run after the first processor.

If your processor returns null, the rest of the pipeline will be skipped

Kind regards
Mahmoud

**Comment by RioTek** [comment]
Yup! That did it. I had "return null" in the processors. Thank you. 

Do you have an example of using EasyRules on all records before persisting to database?

**Comment by benas** [comment]
> Yup! That did it. I had "return null" in the processors. Thank you.

Happy to help!

> Do you have an example of using EasyRules on all records before persisting to database?

Glad to see a combination of easy rules and easy batch :smile: 
I don't have such an example, but I can give you support if needed.
