### ISSUE TITLE
Control how quartz should act when certain job is delayed for a long time

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#260]
As discussed in #201:

> Additionally, I would like to control some policy to instruct how quartz should act when certain job is delayed for a long time (this could be a separated issue but may be solved together with this issue). These policies are specified via API of SimpleScheduleBuilder, but it is not accessible via current easybatch quartz extension API yet.

@niyue Could you please tell me what policies would you see added in the extension?

**Comment by niyue** [comment]
@benas I think Quartz's SimpleScheduleBuilder already considers this and have some built-in policies in its API, and if possible, I would like to see these policies exposed via quartz extension's API. You can find all the built-in misfire policies and their descriptions here:

- http://www.quartz-scheduler.org/api/2.2.1/org/quartz/Trigger.html#MISFIRE_INSTRUCTION_SMART_POLICY
- http://www.quartz-scheduler.org/api/2.2.1/org/quartz/Trigger.html#MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY
- http://www.quartz-scheduler.org/api/2.2.1/org/quartz/SimpleTrigger.html#MISFIRE_INSTRUCTION_FIRE_NOW
- http://www.quartz-scheduler.org/api/2.2.1/org/quartz/SimpleTrigger.html#MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT
- http://www.quartz-scheduler.org/api/2.2.1/org/quartz/SimpleTrigger.html#MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT
- http://www.quartz-scheduler.org/api/2.2.1/org/quartz/SimpleTrigger.html#MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT

In my own case, I would like to use the MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT policy.

**Comment by benas** [comment]
Hi @niyue 

I've added enums for Misfire strategies:

* `JobSchedulerMisfireHandlingInstructionStrategy`
* `JobCronSchedulerMisfireHandlingInstructionStrategy`

And overloaded existing methods in `JobScheduler` to specify the strategy and the repeat count:

* `public void scheduleAt(final org.easybatch.core.job.Job job, final Date startTime, JobSchedulerMisfireHandlingInstructionStrategy strategy, int repeatCount)`
* `public void scheduleAtWithInterval(final org.easybatch.core.job.Job job, final Date startTime, final int interval, JobSchedulerMisfireHandlingInstructionStrategy strategy, int repeatCount)`
* `public void scheduleCron(final org.easybatch.core.job.Job job, final String cronExpression, JobCronSchedulerMisfireHandlingInstructionStrategy strategy)`

You can try these new APIs with version 5.1.0-SNAPSHOT.

Is this what you are looking for?
Please don't hesitate to suggest any improvement.
Looking forward for your feedback.

Kind regards
Mahmoud

**Comment by benas** [comment]
Any update on this?

**Comment by niyue** [comment]
@benas, sorry I overlooked the previous comment. This is the direction I am looking for, and  I don't have a chance to switch to use the latest API at this moment but the overloaded method seems good to me so that I can pass the desired misfire strategy to the underlying Quarts API. Thanks.

**Comment by benas** [comment]
ok good. changes for this feature have been merged in master, will be part of the upcoming release.

Keep tuned.
