### ISSUE TITLE
how to process a block of text instead of a line by line processing?

### ISSUE THREAD

**Issue by jidma** [EasyBatch/easybatch-framework#262]
First of all, thank you for the good work.

The example in the read me demonstrates how to use easybatch and process files in a line by line basis.

```
Job job = new JobBuilder()
         .reader(new FlatFileRecordReader("tweets.csv"))
         .filter(new HeaderRecordFilter())
         .mapper(new DelimitedRecordMapper(Tweet.class, "id", "user", "message"))
         .marshaller(new XmlRecordMarshaller(Tweet.class))
         .writer(new FileRecordWriter("tweets.xml"))
         .batchSize(10)
         .build();

JobReport report = new JobExecutor().execute(job);
```

I have an input file with blocks of text:

```
#    batch
    00001
              test10 test11
              test20 test21
              test30 test31
     end

     #junk data

    batch
    00002
             test40 test41
     end
```

and I would like to input the result as a csv file like this:

    00001;test10;test11
    00001;test20;test21
    00001;test30;test31
    00002;test40;test41

So I need to store data (eg. batch number), then use them to create the subsequent lines until I hit another relevent data, and so on.

Before I dive any further in the code, I would like to know whether this is actually possible? 

Also, my input files are quite massive, is there a way to output progress whenever I hit, say for my example, a new batch number?

Thank you again.

Majid

**Comment by benas** [comment]
Hi Majid,

> First of all, thank you for the good work.

Thank you! 

>  I would like to know whether this is actually possible?

Yes, you can do it with a custom reader. There is a tutorial [here](https://github.com/EasyBatch/easybatch-tutorials/tree/master/src/main/java/org/easybatch/tutorials/advanced/recipes) that may help you. It reads records that are on multiple lines as in your use case.

> Also, my input files are quite massive, is there a way to output progress whenever I hit, say for my example, a new batch number?

A `PipelineListener` is the way to go. It's a callback that allows you to execute custom code before/after each record. There is an example [here](https://github.com/EasyBatch/easybatch-tutorials/tree/master/src/main/java/org/easybatch/tutorials/advanced/metric) that may inspire you. You can find more details on listeners in [the documentation](http://www.easybatch.org/v5.0.0/#_listeners).

Please let me know if this helps.


Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

Does this helped?

Kr
Mahmoud

**Comment by benas** [comment]
I'm closing this issue.

If you have any other question, you can reopen this issue.
