### ISSUE TITLE
Provide access to Job/JobMetrics in Listeners

### ISSUE THREAD

**Issue by jantonecchia** [EasyBatch/easybatch-framework#272]
Would be nice to have access to the Job class from the listeners so we can reset the JobMetrics.   The use-case is a batch agent that runs continually runs consuming batches of data that are grouped by a set id.   When a new set id is received in a batch message I would like to reset the Job name (which currently includes the set id) and I would like to reset the JobMetrics counters

**Comment by benas** [comment]
Thank you for creating this feature request. I was trying to create an example to see how it is impossible as of v5.0 to implement this requirement. Could you please provide a code sample to be able to see at which level access to job/metrics is needed?

**Comment by benas** [comment]
Hi,

Actually you can create a listener that implements both a record listener and a job listener, store what you need in instance variables, and add them to the job report/ metrics at the end of the job. [Here is an example](https://github.com/EasyBatch/easybatch-tutorials/tree/master/src/main/java/org/easybatch/tutorials/advanced/metric).

Does this helps?

Kind regards
Mahmoud

**Comment by jantonecchia** [comment]
Yes I think this will work thanks.   I came up with another workaround using a master job report and the ReportMerger, I think this solution may work too.  Thanks again!

**Comment by benas** [comment]
Oh great! We have two solutions 😄
