### ISSUE TITLE
XmlRecordReader should not escape special characters in tag body

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#277]
As of version 5.0.0, the `XmlRecordReader` escapes special characters in tag bodies (just like tag attributes reported in #67 )

Special characters in tag bodies should be left intact so the payload of the xml record can be correctly processed by record processors.

Here is an example:

```xml
<website name="google">http://www.google.com?query=test&amp;sort=asc</website>
```

The xml reader returns :

```xml
<website name="google">http://www.google.com?query=test&sort=asc</website>
```

but should return the input as is.

Many thanks to @lsoltero35 for reporting this issue!

**Comment by benas** [comment]
Hi @lsoltero35

I've published version 5.1.0-SNAPSHOT with a fix for this issue.

It would be great if you give it a try and tell me if this is ok for you.

Kind regards
Mahmoud

**Comment by lsoltero35** [comment]
Hi @benas, 

The snapshot you published is working, I no longer have the problem with the special chars contained in the tag bodies.

Would it be safe for me to keep using 5.1.0-SNAPSHOT?

**Comment by benas** [comment]
Oh great! thank you for testing.

Yes, you can use the snaphot version, but I'm releasing v5.1 soon.

I'll keep you informed when it is published.

Kr
Mahmoud
