### ISSUE TITLE
Add email sending job listener

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#92]
It is a common requirement to send the report by email at the end of execution. In the same philosophy of writing less code, an `EmailSender` utility class should be added to the `easybatch-tools` module in order to send emails with only providing configuration meta data.

**Comment by nabilov** [comment]
Hello @benas,

This feature is always on standby ? otherwise i can look for a solution .. :)

**Comment by benas** [comment]
Hi @nabilov Glad to see you here!

Sure. You are more than welcome :smile:

**Comment by nabilov** [comment]
Ok friend @benas (7bib) i will analyse and propose a solution to be validated (PR)

**Comment by benas** [comment]
Cool. Many thanks upfront

**Comment by benas** [comment]
Hi @nabilov 

How about contributing this feature to easy batch?

I would be happy to assist!

Kind regards
Mahmoud

**Comment by benas** [comment]
@nabilov This has been added in v5.1.0-SNAPSHOT.

It would be great to give it a try and tell me what do you think.

Kind regards
Mahmoud
